-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `capstone`;
USE SCHEMA `bronze`;

-- COMMAND ----------

SELECT * from samples.nyctaxi.trips

-- COMMAND ----------

SELECT *
FROM read_files('/Volumes/capstone/default/raw/transactions/', FORMAT => 'csv');


-- COMMAND ----------

select *  from capstone.bronze.transactions where 

-- COMMAND ----------

SELECT * FROM read_files('/Volumes/capstone/default/raw/loans/', FORMAT => 'json')LIMIT 20 ;

-- COMMAND ----------

select count(*) from capstone.bronze.accounts

-- COMMAND ----------

select nominee_details.nominee_name as nominee_name,
nominee_details.relationship as relationship
from capstone.bronze.accounts;

-- COMMAND ----------

select count(*) from capstone.bronze.branches

-- COMMAND ----------

select * from capstone.bronze.branches

-- COMMAND ----------

select * from read_files("/Volumes/capstone/default/raw/loans/loans.jsonl",format=>"json")

-- COMMAND ----------



-- COMMAND ----------

select * from capstone.bronze.loans

-- COMMAND ----------

SELECT account_id, COUNT(*) AS dup_count
FROM capstone.bronze.loans
GROUP BY account_id
HAVING COUNT(*) > 1;


-- COMMAND ----------

SELECT *
FROM (
  SELECT *,
         ROW_NUMBER() OVER (
             PARTITION BY account_id
             ORDER BY last_transaction_date DESC
         ) AS rn
  FROM capstone.bronze.accounts
)
WHERE rn = 1;


-- COMMAND ----------

SELECT *
FROM (
  SELECT *,
         ROW_NUMBER() OVER (
             PARTITION BY account_id
             ORDER BY last_updated DESC
         ) AS rn
  FROM capstone.bronze.loans
)
WHERE rn = 1;


-- COMMAND ----------

SHOW TABLES IN capstone.silver;


-- COMMAND ----------



-- COMMAND ----------

-- Step 1: Drop if it exists (safety)
DROP TABLE IF EXISTS silver.loans_cleaned;

-- COMMAND ----------

SHOW TABLES IN capstone.silver;


-- COMMAND ----------

DROP TABLE IF EXISTS silver.customers;
DROP TABLE IF EXISTS silver.accounts;
DROP TABLE IF EXISTS silver.loans;
DROP TABLE IF EXISTS silver.transactions;
DROP TABLE IF EXISTS silver.branches;


-- COMMAND ----------

SHOW MATERIALIZED VIEW IN capstone.gold;


-- COMMAND ----------

SELECT current_catalog();


-- COMMAND ----------


